### ISSUE TITLE
changing the structure

### ISSUE THREAD

**Issue by vclteam** [JamesRandall/Simple-Paging-Grid#12]
is there a way to add or remove a column after the initial creation?

**Comment by JamesRandall** [comment]
Currently no - but its a good idea and I'll look to add it as a feature: add, insert and remove sets of columns and rebind.

Depending on what you are doing a workaround as an interim might be to have two grids, and show and hide them. Heavy and clunky I accept.

I'll leave this issue open until I add the feature. I'll probably do it this weekend, I always enjoy working on this grid!

**Comment by vclteam** [comment]
great

**Comment by vclteam** [comment]
BTW

i think u have an issue with "_refreshData"

if u trying to refreshthe grid with new array (not new ajax call) its will not works
already fixed it

my suggestion is

if (newDataUrl !== undefined) {
//check here if its string or array
                this._settings.dataUrl = newDataUrl;
                that._currentPage = 0;
            }

**Comment by JamesRandall** [comment]
Thanks - can you check if you are using the latest version (0.5.0.2) - I issued some fixes for this problem in here. I think you're on 0.5.0.1 due to your mention of newDataUrl - I renamed that to newBinding as part of the fix. Previously I hadn't really considered people rebinding the grid with the array.

If you are using 0.5.0.2 and there is still a problem then let me know.

**Comment by vclteam** [comment]
correct

**Comment by JamesRandall** [comment]
I'm still considering this for a future version but for the time being I've left it as is. You can add a column by recreating the grid.
