### ISSUE TITLE
External JavaScript refresh

### ISSUE THREAD

**Issue by wrhighfield** [JamesRandall/Simple-Paging-Grid#2]
Not sure if there is a clean way to do this but be able to refresh the grid from an external JavaScript call.  This could be useful if you have search criteria and you want the grid to refresh when an item in a dropdown is selected or just a simple refresh button.

**Comment by JamesRandall** [comment]
You can do this at the moment but it's undocumented simply because I'm in the process of changing it and its really really scruffy. When I started the grid I hadn't written any plugins before and the grid was supposed to be really really simple - that started to change and I need to do some refactoring.

Basically there is a refresh function but it's not attached to the jQuery object but to the actual HTML element. If you create a grid:

var $grid = $("#exampleGrid").simplePagingGrid({ ... });

You can then do:

$grid.get(0).refreshData(optionalUrlString);

You can supply an optional URL if, for example, you want to pass some search text in on the query string. It works fine and I've used it a lot its just scruffy. You can also use refreshData with the post data methods.

I'm currently in the process of updating the grid to expose a proper plugin model at which point this will be properly documented and not so hacky. Probably be released in about 2 weeks time.

In the meantime hope that gets you going.

**Comment by wrhighfield** [comment]
Cool, thanks.

Yeah I was fooling around with the same code you mentioned and it seemed to work but was not 100% sure about it.

So far I am really liking the plugin, I was able to wire up my MVC app pretty quickly and get it loading data.

**Comment by JamesRandall** [comment]
I've started to add external interactions in the 0.5 build including this, now in the development branch along with some documentation:

https://github.com/JamesRandall/Simple-Paging-Grid/tree/development

Will be moved across to the master branch shortly and I'll close this then.

**Comment by JamesRandall** [comment]
In 0.5
